#!/bin/sh

#
# Copyright © 2015-2021 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, to run this script, type that shell name before the whole command
#       line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced functionality shells are not supported.
#
#   (2) You need to have a JDK installed. This script assumes that java and javac
#       are in your PATH. If not, you need to set JAVA_HOME.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing / for empty path which can be removed
    [ -h "$app_path" ]
do
    app_path=$APP_HOME
    # need to resolve until we can't anymore
    [ -h "$APP_HOME" ] && break
    # avoid infinite loop with broken symlinks
    [ -e "$APP_HOME" ] || break
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=${APP_HOME:-./}

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=1024

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )        darwin=true  ;; #(
  MSYS* | MINGW* ) msys=true   ;; #(
  NonStop* )       nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        JAVACMD=$JAVA_HOME/bin/java
    else
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      '' | *NA* | *not* | *NFD* )
        warn "Could not determine max file descriptor limit."
    ;;
      * )
        MAX_FD_TEST=$(ulimit -n)
        if [ "$?" -ne 0 ] ; then
            warn "Could not determine max file descriptor limit."
        else
            case $MAX_FD_TEST in  #(
              '' | *NA* | *not* | *NFD* | *unlimited* )
                warn "Could not determine max file descriptor limit."
            ;;
              * )
                MAX_FD=$MAX_FD_TEST
            esac
        fi
        if [ "$MAX_FD" -gt 0 ] 2>/dev/null; then
            ulimit -n "$MAX_FD" || warn "Could not set max file descriptor limit to $MAX_FD"
        fi
    esac
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
# We use eval to handle the arguments properly
# The arguments are separated by unquoted spaces, but we need to handle quoted arguments
# and escape special characters

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
JVM_OPTS="$DEFAULT_JVM_OPTS"

# Publish the JVM options for the current execution
if [ -n "$JAVA_OPTS" ]; then
    JVM_OPTS="$JVM_OPTS $JAVA_OPTS"
fi
if [ -n "$GRADLE_OPTS" ]; then
    JVM_OPTS="$JVM_OPTS $GRADLE_OPTS"
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        JAVACMD=$JAVA_HOME/bin/java
    else
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Determine the Java version
JAVACMD_OUTPUT=$( "$JAVACMD" -version 2>&1 )
JAVACMD_EXIT=$?

if [ $JAVACMD_EXIT -ne 0 ] ; then
    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Check if we are running on Java 9 or later
# We need to extract the version number from the version string
# Java 9 and later output version strings like "java 9", "java 9.0.1", "java 10", "java 10.0.1", etc.
# Java 8 and earlier output version strings like "java version \"1.8.0_101\""

JAVACMD_VERSION=$(echo "$JAVACMD_OUTPUT" | sed 's/.*version "\([^"]*\)".*/\1/; 2>/dev/null')

if [ -z "$JAVACMD_VERSION" ]; then
    JAVACMD_VERSION=$(echo "$JAVACMD_OUTPUT" | sed 's/version "\([^"]*\)".*/\1/; 2>/dev/null')
fi

if [ -z "$JAVACMD_VERSION" ]; then
    JAVACMD_VERSION=$(echo "$JAVACMD_OUTPUT" | sed 's/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/; 2>/dev/null')
fi

# Check if the version is at least 9
JAVACMD_VERSION_MAJOR=$(echo "$JAVACMD_VERSION" | sed 's/\([0-9][0-9]*\)\.[0-9][0-9]*\.[0-9][0-9]*.*/\1/; 2>/dev/null')

if [ "$JAVACMD_VERSION_MAJOR" -ge 9 ] 2>/dev/null; then
    # For Java 9 and later, we need to add the --add-opens flag to avoid illegal access errors
    JVM_OPTS="$JVM_OPTS \"--add-opens java.base/java.util=ALL-UNNAMED\" \"--add-opens java.base/java.lang=ALL-UNNAMED\""
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
# We use eval to handle the arguments properly
# The arguments are separated by unquoted spaces, but we need to handle quoted arguments
# and escape special characters

# Build the java command line
JVM_ARGS=("${JVM_OPTS}" "-Dorg.gradle.appname=$APP_BASE_NAME" "-classpath" "$CLASSPATH" "org.gradle.wrapper.GradleWrapperMain" "$@")

# Start the JVM
# shellcheck disable=SC2206
JVM_COMMAND="$JAVACMD ${JVM_ARGS[*]}"

# Execute the JVM command
eval "$JVM_COMMAND"
